### ISSUE TITLE
add info about ritlug servers

### ISSUE THREAD

**Issue by axk4545** [RITlug/runbook#3]
-where are the servers located?
-who do we contact to access them?
-how do we access them?
any other relevant info.

**Comment by thenaterhood** [comment]
Hey @abkahrs! Thanks for the input!

You actually have two issues here. It's preferable to open a separate issue for each item so they can be tracked individually. I gotcha covered though, I'll break it apart.

**Comment by jflory7** [comment]
Following up here now…

@Serubin, do we have access to any of the old servers or is it only Titan now?

**Comment by Serubin** [comment]
Crap. That was ages ago.
I have no idea about the old servers... @thenaterhood would know best.

Titan is fully functional and we have access. We've now got a gitlab instance set up there as well as the tgbots. I'm more than willing to setup VMs for folks to play around with - normal RIT polices will apply as it's their RIT. 

As a small note: I need to fix up our current debian template image. If folks want to help create other images for proxmox/kvm I'm happy to have the help. I've got some better security practices that I need to put into place on the next round of templates.

**Comment by thenaterhood** [comment]
The old servers are in the bioinformatics datacenter I'm pretty sure. They're in various states of disrepair and outdatedness at this point.

There are five of them. Since you've superceded them, you should probably get in touch with the bioinformatics sysadmin or ITS to get in and pull them so they're not taking up space.

**Comment by Serubin** [comment]
I can handle this.
@thenaterhood Any suggestions on what to do with them once we get them out?

**Comment by abkahrs** [comment]
@thenaterhood, @Serubin I know I am not @thenaterhood but for those that are unneeded, they could go to an e-waste bin after being stripped of anything that may be useful. Alternatively, we could sell them for scrap ourselves or sell them to members

**Comment by thenaterhood** [comment]
I think we talked about this already today in another channel.

You can talk to RIT ITS, they may have suggestions. I don't know if they should just get tossed in the RIT e-waste bins, since e-waste usually gets hauled away for recycling at a cost.

Selling them as a club could get sketchy because of non-profit status and falling under the institute financial umbrella. You might need to run something like that past the clubs office and find out the correct way to do it. I don't think you'd get too much for them with how old they are and some may even have had hardware failures either way.

If you made them available to interested club members or kept them yourselves for personal use, it doesn't matter what gets done with them after that point. You might just want to document the handoff to keep things formal "just in case", though the club didn't need to go through any official process to receive them because of how they were donated.

**Comment by axk4545** [comment]
I know we are all pretty busy but are there any updates on this?

**Comment by Serubin** [comment]
@axk4545 I found the sys admin. Waiting to hear back.

**Comment by jflory7** [comment]
Migrating this issue to RITlug/tasks#8, closing issue here.
